name: "Download PA vote stats"

on:
  schedule:
    - cron: "0 21 * * 2" # Every Tuesday at 21:00 UTC (16:00 EST)
  workflow_dispatch:

jobs:
  download:
    name: Download
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: run-script
        name: Run download script
        run: |
          . ./download.sh
      - id: add-and-commit
        name: Add and commit
        run: |
          git add .
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Latest data"
      - id: push
        name: Push
        run: |
          git push
